# coding: utf-8

"""
    iLoveVideoEditor API

    Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RenderWebhookPayload(BaseModel):
    """
    JSON body POSTed to webhook targets on terminal render states.
    """ # noqa: E501
    event: StrictStr
    id: UUID = Field(description="Render job ID.")
    status: StrictStr
    stage: Optional[StrictStr] = None
    progress: Optional[StrictInt] = None
    url: Optional[StrictStr] = None
    outputs: Optional[List[Dict[str, Any]]] = None
    duration: Optional[Union[StrictFloat, StrictInt]] = None
    width: Optional[StrictInt] = None
    height: Optional[StrictInt] = None
    template_id: Optional[StrictStr] = Field(default=None, alias="templateId")
    cost: Optional[Union[StrictFloat, StrictInt]] = None
    error: Optional[StrictStr] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    completed_at: Optional[datetime] = Field(default=None, alias="completedAt")
    __properties: ClassVar[List[str]] = ["event", "id", "status", "stage", "progress", "url", "outputs", "duration", "width", "height", "templateId", "cost", "error", "createdAt", "completedAt"]

    @field_validator('event')
    def event_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['render.completed', 'render.failed']):
            raise ValueError("must be one of enum values ('render.completed', 'render.failed')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['completed', 'failed']):
            raise ValueError("must be one of enum values ('completed', 'failed')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RenderWebhookPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RenderWebhookPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event": obj.get("event"),
            "id": obj.get("id"),
            "status": obj.get("status"),
            "stage": obj.get("stage"),
            "progress": obj.get("progress"),
            "url": obj.get("url"),
            "outputs": obj.get("outputs"),
            "duration": obj.get("duration"),
            "width": obj.get("width"),
            "height": obj.get("height"),
            "templateId": obj.get("templateId"),
            "cost": obj.get("cost"),
            "error": obj.get("error"),
            "createdAt": obj.get("createdAt"),
            "completedAt": obj.get("completedAt")
        })
        return _obj


