# coding: utf-8

"""
    iLoveVideoEditor API

    Cloud video rendering API for iLoveVideoEditor. Submit a `VideoJSON` payload, queue a render job, and download the resulting MP4.  **Authentication** - **API Key** (`x-api-key` header) — accepted by render pipeline and tool endpoints. - **Bearer Token** (`Authorization: Bearer <jwt>`) — required for user-scoped project, asset, billing, and webhook endpoints. - Many endpoints accept either form of authentication.  **SDKs** Official typed SDKs are available for JavaScript/TypeScript, PHP, Python, Ruby, and Go. See https://ilovevideoeditor.com/docs/sdks  **Outbound Webhooks** Render lifecycle events (`render.completed`, `render.failed`) are delivered to your endpoints as signed HTTP POST requests. See the `Webhooks` tag and the root-level `x-webhook-docs` extension for the payload format (`RenderWebhookPayload`), signature headers, HMAC verification, and the retry policy.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkflowRunStep(BaseModel):
    """
    WorkflowRunStep
    """ # noqa: E501
    id: UUID
    workflow_run_id: UUID = Field(alias="workflowRunId")
    step_index: StrictInt = Field(alias="stepIndex")
    step_type: StrictStr = Field(alias="stepType")
    name: Optional[StrictStr] = None
    config: Optional[Dict[str, Any]] = None
    status: Optional[StrictStr] = None
    input_url: Optional[StrictStr] = Field(default=None, alias="inputUrl")
    output_url: Optional[StrictStr] = Field(default=None, alias="outputUrl")
    output_key: Optional[StrictStr] = Field(default=None, alias="outputKey")
    rendition_id: Optional[StrictStr] = Field(default=None, alias="renditionId")
    error: Optional[StrictStr] = None
    response_status: Optional[StrictInt] = Field(default=None, alias="responseStatus")
    metadata: Optional[Dict[str, Any]] = None
    retry_count: Optional[StrictInt] = Field(default=None, alias="retryCount")
    max_retries: Optional[StrictInt] = Field(default=None, alias="maxRetries")
    logs: Optional[List[Dict[str, Any]]] = None
    started_at: Optional[datetime] = Field(default=None, alias="startedAt")
    completed_at: Optional[datetime] = Field(default=None, alias="completedAt")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "workflowRunId", "stepIndex", "stepType", "name", "config", "status", "inputUrl", "outputUrl", "outputKey", "renditionId", "error", "responseStatus", "metadata", "retryCount", "maxRetries", "logs", "startedAt", "completedAt", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowRunStep from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if config (nullable) is None
        # and model_fields_set contains the field
        if self.config is None and "config" in self.model_fields_set:
            _dict['config'] = None

        # set to None if input_url (nullable) is None
        # and model_fields_set contains the field
        if self.input_url is None and "input_url" in self.model_fields_set:
            _dict['inputUrl'] = None

        # set to None if output_url (nullable) is None
        # and model_fields_set contains the field
        if self.output_url is None and "output_url" in self.model_fields_set:
            _dict['outputUrl'] = None

        # set to None if output_key (nullable) is None
        # and model_fields_set contains the field
        if self.output_key is None and "output_key" in self.model_fields_set:
            _dict['outputKey'] = None

        # set to None if rendition_id (nullable) is None
        # and model_fields_set contains the field
        if self.rendition_id is None and "rendition_id" in self.model_fields_set:
            _dict['renditionId'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if response_status (nullable) is None
        # and model_fields_set contains the field
        if self.response_status is None and "response_status" in self.model_fields_set:
            _dict['responseStatus'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if logs (nullable) is None
        # and model_fields_set contains the field
        if self.logs is None and "logs" in self.model_fields_set:
            _dict['logs'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['startedAt'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowRunStep from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "workflowRunId": obj.get("workflowRunId"),
            "stepIndex": obj.get("stepIndex"),
            "stepType": obj.get("stepType"),
            "name": obj.get("name"),
            "config": obj.get("config"),
            "status": obj.get("status"),
            "inputUrl": obj.get("inputUrl"),
            "outputUrl": obj.get("outputUrl"),
            "outputKey": obj.get("outputKey"),
            "renditionId": obj.get("renditionId"),
            "error": obj.get("error"),
            "responseStatus": obj.get("responseStatus"),
            "metadata": obj.get("metadata"),
            "retryCount": obj.get("retryCount"),
            "maxRetries": obj.get("maxRetries"),
            "logs": obj.get("logs"),
            "startedAt": obj.get("startedAt"),
            "completedAt": obj.get("completedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


